language: php

sudo: false

env:
  global:
    - COLLECT_COVERAGE=true

matrix:
  include:
    - php: 5.4
      env: COLLECT_COVERAGE=false
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
      env: COLLECT_COVERAGE=false
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-dist

script:
  - composer test

after_script:
 - if [ "$COLLECT_COVERAGE" == "true" ]; then wget https://scrutinizer-ci.com/ocular.phar; && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
